### ISSUE TITLE
Compilation error Arduino(AVR) vs ESP32-C3

### ISSUE THREAD

**Issue by Diolum** [upiir/arduino_round_lcd_display#1]
Hi,

First of all thanks for all your work.

I have a problem compiling for ESP32-C3.

For an Arduino Uno I get:

```
warning: invalid conversion from 'const unsigned char*' to 'byte* {aka unsigned char*}' [-fpermissive]
   draw_image(55, 99, 123, 47, gImage_shifter_logo_M_123x47px);
note:   initializing argument 5 of 'void draw_image(int, int, int, int, byte*)'
 void draw_image(int x, int y, int width, int height, byte image_array[]) {
warning: invalid conversion from 'const unsigned char*' to 'byte* {aka unsigned char*}' [-fpermissive]
   draw_image_tinted(30, 52, 24, 28, gImage_shifter_digit_R_24x28px, color_inactive);
note:   initializing argument 5 of 'void draw_image_tinted(int, int, int, int, byte*, unsigned int)'
 void draw_image_tinted(int x, int y, int width, int height, byte image_array[], unsigned int tint) {
.......
```

It compiles and works on Arduino nonetheless.

But with an ESP32 C3 I get:

```
error: invalid conversion from 'const unsigned char*' to 'byte*' {aka 'unsigned char*'} [-fpermissive]
  255 |   draw_image(55, 99, 123, 47, gImage_shifter_logo_M_123x47px);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                               |
      |                               const unsigned char*

note:   initializing argument 5 of 'void draw_image(int, int, int, int, byte*)'
  182 | void draw_image(int x, int y, int width, int height, byte image_array[]) {
      |                                                      ~~~~~^~~~~~~~~~~~~

.......

exit status 1

Compilation error: invalid conversion from 'const unsigned char*' to 'byte*' {aka 'unsigned char*'} [-fpermissive]
```

And it does not compile.

Can you explain this or fix the code to get it working on esp32 as well?

Thanks

**Comment by IAmOrion** [comment]
@Diolum 

I got this to work on my ESP32C3 by doing the following...

Connect the pins accordingly:
```
LCD                 ESP32C3
--------------------------
GND                  GND
VCC                  VCC
SCL                   4
SDA                   6
RES                   1
DC                    8
CS                    9
BLK                  10
```

Next, modify the pin definitions in the main file

```
// ------ ESP32C3
#define LED   10
#define CS    9
#define RS    8 // aka DC
#define RESET 1
```
<img width="400" alt="Screenshot 2024-06-11 at 03 18 25" src="https://github.com/upiir/arduino_round_lcd_display/assets/3501380/79b628ec-2ef2-414f-a8ab-c1251204f1d2">

Then, goto to void setup() and change/replace the 4 pinMode statements and digitaWrite statements with this:

```
  pinMode(LED, OUTPUT);
  pinMode(CS, OUTPUT);
  pinMode(RS, OUTPUT);
  pinMode(RESET, OUTPUT);

  digitalWrite(LED, HIGH);
  digitalWrite(CS, HIGH);
  digitalWrite(RS, HIGH);
  digitalWrite(RESET, HIGH);
```
<img width="231" alt="Screenshot 2024-06-11 at 03 19 57" src="https://github.com/upiir/arduino_round_lcd_display/assets/3501380/4987915f-6f7b-439c-9b33-aaa3cc558d40">

Lastly, in images.h, remove ```const ``` leaving just ```unsigned char``` for ***each*** entry (8 in total)

<img width="824" alt="Screenshot 2024-06-11 at 03 21 01" src="https://github.com/upiir/arduino_round_lcd_display/assets/3501380/18ebeceb-3866-4a40-85bf-8ce2557f0826">

I was able to successfully get this demo working by doing that.
FWIW The breakout board I'm using is this: [https://www.aliexpress.com/item/1005006451672646.html](https://www.aliexpress.com/item/1005006451672646.html)


https://github.com/upiir/arduino_round_lcd_display/assets/3501380/2bcc8deb-a429-4a2f-9e6a-880291c25695

Hope that helps

**Comment by Diolum** [comment]
Sorry for the late response.

The compiling and upload works but no image.

i have donne exactly what you said.

Blue led is blinking fast si the code is running. but nothing.

What board are you using in the board selector and with which parameters?

I'm using exactly the same board with LOLIN C3 MINI selected with default parameters.
![Capture d’écran 2024-06-17 à 00 03 15](https://github.com/upiir/arduino_round_lcd_display/assets/35182033/d1e103fe-f84e-4f8c-80a6-6f42fd778181)

**Comment by IAmOrion** [comment]
> What board are you using in the board selector and with which parameters?

@Diolum ESP32C3 Dev Module

<img width="529" alt="Screenshot 2024-06-16 at 23 29 06" src="https://github.com/upiir/arduino_round_lcd_display/assets/3501380/f32ea643-8006-4eab-a69c-ad9e54d243ca">

The pin definitions are different between the 2 boards! Try using the same as me or adjust your wiring to match.

ESP32C3 Pin definitions:

```
static const uint8_t TX = 21;
static const uint8_t RX = 20;

static const uint8_t SDA = 8;
static const uint8_t SCL = 9;

static const uint8_t SS    = 7;
static const uint8_t MOSI  = 6;
static const uint8_t MISO  = 5;
static const uint8_t SCK   = 4;

static const uint8_t A0 = 0;
static const uint8_t A1 = 1;
static const uint8_t A2 = 2;
static const uint8_t A3 = 3;
static const uint8_t A4 = 4;
static const uint8_t A5 = 5;
```

Lolin C3 Mini Pin Definitions:

```
static const uint8_t TX = 21;
static const uint8_t RX = 20;

static const uint8_t SDA = 8;
static const uint8_t SCL = 10;

static const uint8_t SS    = 5;
static const uint8_t MOSI  = 4;
static const uint8_t MISO  = 3;
static const uint8_t SCK   = 2;

static const uint8_t A0 = 0;
static const uint8_t A1 = 1;
static const uint8_t A2 = 2;
static const uint8_t A3 = 3;
static const uint8_t A4 = 4;
static const uint8_t A5 = 5;
```

As you can see, SCL, SS, MOSI, MISO, SCK are defined differently so if using the same board and wiring as me, select ESP32C3 Dev Module in the IDE

**Comment by Diolum** [comment]
selecting the correct board was the solution. thanks a lot
